#!/bin/bash

docker buildx create --name container --driver docker-container --use
docker buildx build \
  -f ./Dockerfile.$DOCKER_TAG \
  -t $IMAGE_NAME:$DOCKER_TAG \
  --sbom=generator=docker/scout-sbom-indexer:latest --provenance=mode=max \
  --output=type=registry \
  .
